{-# OPTIONS --cubical --exact-split #-}

module Everything where

import Cubical.Structures.Arity
import Cubical.Structures.Coh
import Cubical.Structures.Eq
import Cubical.Structures.Free
import Cubical.Structures.Gpd.Mon.Desc
import Cubical.Structures.Gpd.Mon.Free
import Cubical.Structures.Gpd.Mon.List
import Cubical.Structures.Gpd.SMon.Free
import Cubical.Structures.Gpd.SMon.SList
import Cubical.Structures.Prelude
import Cubical.Structures.Prelude.TODO
import Cubical.Structures.Set.CMon.Bag
import Cubical.Structures.Set.CMon.Bag.Base
import Cubical.Structures.Set.CMon.Bag.FinExcept
import Cubical.Structures.Set.CMon.Bag.Free
import Cubical.Structures.Set.CMon.Bag.ToCList
import Cubical.Structures.Set.CMon.CList
import Cubical.Structures.Set.CMon.Desc
import Cubical.Structures.Set.CMon.Free
import Cubical.Structures.Set.CMon.PList
import Cubical.Structures.Set.CMon.QFreeMon
import Cubical.Structures.Set.CMon.SList
import Cubical.Structures.Set.CMon.SList.Base
import Cubical.Structures.Set.CMon.SList.Count
import Cubical.Structures.Set.CMon.SList.Head
import Cubical.Structures.Set.CMon.SList.Length
import Cubical.Structures.Set.CMon.SList.Membership
import Cubical.Structures.Set.CMon.SList.Seely
import Cubical.Structures.Set.CMon.SList.Sort
import Cubical.Structures.Set.CMon.SList.Sort.Base
import Cubical.Structures.Set.CMon.SList.Sort.Equiv
import Cubical.Structures.Set.CMon.SList.Sort.Order
import Cubical.Structures.Set.CMon.SList.Sort.Sort
import Cubical.Structures.Set.Empty
import Cubical.Structures.Set.Mon.Array
import Cubical.Structures.Set.Mon.Desc
import Cubical.Structures.Set.Mon.Free
import Cubical.Structures.Set.Mon.List
import Cubical.Structures.Sig
import Cubical.Structures.Str
import Cubical.Structures.Tree

import Cubical.Structures.Arity
import Cubical.Structures.Coh
import Cubical.Structures.Eq
import Cubical.Structures.Free
import Cubical.Structures.Gpd.Mon.Desc
import Cubical.Structures.Gpd.Mon.Free
import Cubical.Structures.Gpd.Mon.List
import Cubical.Structures.Gpd.SMon.Free
import Cubical.Structures.Gpd.SMon.SList
import Cubical.Structures.Prelude
import Cubical.Structures.Prelude.TODO
import Cubical.Structures.Set.CMon.Bag
import Cubical.Structures.Set.CMon.Bag.Base
import Cubical.Structures.Set.CMon.Bag.FinExcept
import Cubical.Structures.Set.CMon.Bag.Free
import Cubical.Structures.Set.CMon.Bag.ToCList
import Cubical.Structures.Set.CMon.CList
import Cubical.Structures.Set.CMon.Desc
import Cubical.Structures.Set.CMon.Free
import Cubical.Structures.Set.CMon.PList
import Cubical.Structures.Set.CMon.QFreeMon
import Cubical.Structures.Set.CMon.SList
import Cubical.Structures.Set.CMon.SList.Base
import Cubical.Structures.Set.CMon.SList.Count
import Cubical.Structures.Set.CMon.SList.Head
import Cubical.Structures.Set.CMon.SList.Length
import Cubical.Structures.Set.CMon.SList.Membership
import Cubical.Structures.Set.CMon.SList.Seely
import Cubical.Structures.Set.CMon.SList.Sort
import Cubical.Structures.Set.CMon.SList.Sort.Base
import Cubical.Structures.Set.CMon.SList.Sort.Equiv
import Cubical.Structures.Set.CMon.SList.Sort.Order
import Cubical.Structures.Set.CMon.SList.Sort.Sort
import Cubical.Structures.Set.Empty
import Cubical.Structures.Set.Mon.Array
import Cubical.Structures.Set.Mon.Desc
import Cubical.Structures.Set.Mon.Free
import Cubical.Structures.Set.Mon.List
import Cubical.Structures.Sig
import Cubical.Structures.Str
import Cubical.Structures.Tree
